### ISSUE TITLE
Possibility for a unified API on `compute_acceleration`

### ISSUE THREAD

**Issue by jackyarndley** [JuliaSpaceMissionDesign/AstroModels.jl#2]
Would it be possible for a unified API to be developed for `compute_acceleration` in addition to `compute_potential`. This would make it more streamlined to use several gravity models together, for example a 2-body + spherical harmonic model. 

Additionally, could `μ` and `radius` be optional parameters rather than required parameters in these models? For example, the spherical harmonic model already has `μ` and `radius` defined within the struct.

I'm happy to draft a PR if you think this is sensible.

**Comment by andreapasquale94** [comment]
@jackyarndley, as you might have noticed this package is still in development. 
I had to review some things in `FrameTransformations.jl` in the last months and now finally have some time to dedicate to this package and finalize it.

Atm, a unified API was avoided because the different models require different data, e.g. spherical harmonics require the coefficients, (C & S), a polyhedron model requires the shape model of the body, etc.

The basic idea here was to follow [JSMDInterfaces.jl/Models](https://github.com/JuliaSpaceMissionDesign/JSMDInterfaces.jl/blob/main/src/Models.jl) interface for models serialization/de-serialization and I would like to extend this interface also for their evaluation. 
That would be for sure sensible in case you're still interested.

**Comment by andreapasquale94** [comment]
@jackyarndley there is already an interface for acceleration computation if this is what you intended though:

https://github.com/JuliaSpaceMissionDesign/AstroModels.jl/blob/72d0cb00783f091d333be7ff015b6ce12b472f15/src/interface.jl#L24

**Comment by jackyarndley** [comment]
Hi @andreapasquale94, I see - thanks for demonstrating that. I may have been a bit confused due to the in-development state of the package. I will close this issue for now.
